vocablizer/listings/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    # path('my_flashcards/', views.my_flashcards, name='my_flashcards'),
]

vocablizer/vocablizer/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('english/', views.english_list, name='english-list'),
    path('english/<int:english_id>/', views.english_detail, name='english-detail'),
    path('english/<int:english_id>/edit/', views.english_edit, name='english-edit'),
    path('english/<int:english_id>/delete/', views.english_delete, name='english-delete'),
    path('english/add/', views.english_add, name='english-add'),

    path('example/', views.example_list, name='example-list'),
    path('example/<int:example_id>/', views.example_detail, name='example-detail'),
    path('example/<int:example_id>/edit/', views.example_edit, name='example-edit'),    
    path('example/<int:example_id>/delete/', views.example_delete, name='example-delete'),
    path('example/add/', views.example_add, name='example-add'),

    path('about/', views.about, name='about'),

    path('contact-us/', views.contact, name='contact'),
    path('email-sent/', views.email_sent, name='email-sent'),

]

vocablizer/listings/models.py
from django import forms
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
class English(models.Model):

    class Genre(models.TextChoices):
        NOUN = 'NOUN'
        VERB = 'VERB'
        ADJECTIVE = 'ADJECTIVE'
        ADVERB = 'ADVERB'
        PRONOUN = 'PRONOUN'
        PREPOSITION = 'PREPOSITION'
        CONJUNCTION = 'CONJUNCTION'
        INTERJECTION = 'INTERJECTION'
    id = models.fields.AutoField(primary_key=True)
    word = models.fields.CharField(max_length=100)
    meaning = models.fields.CharField(max_length=100, blank=True)
    rank = models.fields.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    active = models.fields.BooleanField(default=True)
    genre = models.fields.CharField(max_length=100, choices=Genre.choices)
    created_at = models.fields.DateTimeField(auto_now_add=True)
    updated_at = models.fields.DateTimeField(auto_now=True)

    def __str__(self):
        return f"\"{self.word}\"" 
    
class EnglishForm(forms.ModelForm):
    class Meta:
        model = English
        exclude = ['active', 'rank']
class Example(models.Model):
    id = models.fields.AutoField(primary_key=True)
    english = models.ForeignKey(English, on_delete=models.CASCADE)
    example = models.fields.CharField(max_length=100)
    created_at = models.fields.DateTimeField(auto_now_add=True)
    updated_at = models.fields.DateTimeField(auto_now=True)

class ExampleForm(forms.ModelForm):
    class Meta:
        model = Example
        fields = "__all__"

vocablizer/listings/forms.py
from django import forms

class ContactUsForm(forms.Form):
   name = forms.CharField(required=False)
   email = forms.EmailField()
   message = forms.CharField(max_length=1000)

vocablizer/listings/views.py
from django.core.mail import send_mail
from listings.forms import ContactUsForm
from listings.models import English, EnglishForm, Example, ExampleForm
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect

def english_list(request):
    english_words = English.objects.all()
    return render(request,
                   "listings/english_list.html",
                  {'words': english_words})

def english_detail(request, english_id):
    english_word = get_object_or_404(English, pk=english_id) # pk = primary key. Generate error404: generic error page
    return render(request,
                   "listings/english_detail.html",
                  {'english_word': english_word})

def english_add(request):
    if request.method == 'POST':
        form = EnglishForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('english-list')
    else:
        form = EnglishForm()        
    return render(request,
                     "listings/english_add.html",
                     {'form': form})

def english_edit(request, english_id):
    english_word = get_object_or_404(English, pk=english_id)
    if request.method == 'POST':
        form = EnglishForm(request.POST, instance=english_word)
        if form.is_valid():
            form.save()
            return redirect('english-detail', english_word.id)
    else:
        form = EnglishForm(instance=english_word)
    return render(request,
                    "listings/english_edit.html",
                    {'form': form})

def english_delete(request, english_id):
    english_word = get_object_or_404(English, pk=english_id)
    if request.method == 'POST':
        english_word.delete()
        return redirect('english-list')

    return render(request,
                    "listings/english_delete.html",
                    {'english_word': english_word})

def example_add(request):
    if request.method == "POST":
        form = ExampleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('example-list')
    else:
        form = ExampleForm()
    return render(request,
                   "listings/example_add.html",
                   {'form': form})

def example_list(request):
    examples = Example.objects.all()
    return render(request,
                   "listings/example_list.html",
                  {'examples': examples})

def example_detail(request, example_id):
    example = get_object_or_404(Example, pk=example_id) # pk = primary key. Generate error404: generic error page
    return render(request,
                   "listings/example_detail.html",
                  {'example': example})

def example_edit(request, example_id):
    example = get_object_or_404(Example, pk=example_id)
    if request.method == 'POST':
        form = ExampleForm(request.POST, instance=example)
        if form.is_valid():
            form.save()
            return redirect('example-detail', example.id)
    else:
        form = ExampleForm(instance=example)
    return render(request,
                    "listings/example_edit.html",
                    {'form': form})

def example_delete(request, example_id):
    example = get_object_or_404(Example, pk=example_id)
    if request.method == 'POST':
        example.delete()
        return redirect('example-list')

    return render(request,
                    "listings/example_delete.html",
                    {'example': example})


def about(request):
    return render(request,
                   'listings/about.html')

def contact(request):
    if request.method == 'POST':
        form = ContactUsForm(request.POST)

        if form.is_valid():
            send_mail(
                subject='Website Inquiry : from ' + form.cleaned_data['email'],
                message=form.cleaned_data['message'],
                from_email=form.cleaned_data['email'],
                recipient_list=['calik63658@tiervio.com']
            )
        return redirect('email-sent')

    else:
        form = ContactUsForm()

    return render(request,
                    'listings/contact.html',
                {'form': form})

def email_sent(request):
    return render(request,
                   'listings/email_sent.html')

vocablizer/listings/templates/listings/about.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1>About Page</h1>
    <p>Welcome to our website! This is the about page.</p>

{% endblock %}

vocablizer/listings/templates/listings/base.html
<!DOCTYPE html>

{% load static %}

<html>
    <head><title>Vocablizer</title></head>
    <link rel="stylesheet" href="{% static 'listings/styles.css' %}" />
    <body>

        <nav>
            <ul>
                <li><a href="{% url 'english-list' %}">English list</a></li>
                <li><a href="{% url 'example-list' %}">Examples</a></li>
                <li><a href="{% url 'about' %}">About</a></li>
                <li><a href="{% url 'contact' %}">contact</a></li>
            </ul>

        {% block content %}{% endblock %}
    </body>
</html>

vocablizer/listings/templates/listings/contact.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1>Contact Information</h1>
    <p>Name: John Doe</p>
    <p>Email: johndoe@example.com</p>
    <p>Phone: 123-456-7890</p>
    <p>Address: 123 Main Street, City, State, ZIP</p>

    <h1>Contact us: </h1>

    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    

{% endblock %}

vocablizer/listings/templates/listings/email_sent.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Email Sent</h1>
<p>Your email has been sent. We will get back to you soon.</p>

{% endblock %}

vocablizer/listings/templates/listings/english_add.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1>Add a new English word</h1>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send">
    </form>
    
{% endblock %}

vocablizer/listings/templates/listings/english_delete.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1>Delete english word : {{english_word.word}}</h1>

    <p>Are you sure you want to delete this word?</p>
    
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes, I'm sure.">    
    </form>

{% endblock %}

vocablizer/listings/templates/listings/english_detail.html
{% extends 'listings/base.html' %}

{% block content %}
    <h2> Detail for {{english_word.word}} :</h2>
    <ul>
        <li>Genre: {{english_word.get_genre_display}}</li>
        {% if english_word.meaning %}
            <li>Meaning: {{english_word.meaning}}</li>
        {% endif %}
        {% for example in english_word.example_set.all%}
            <li> <a href="{% url 'example-detail' example.id%}"> Example {{ forloop.counter }}</a>
                : {{example.example}}</li> 
        {% endfor %}
        <li>Created at: {{english_word.created_at}}</li>
        <li>Updated at: {{english_word.updated_at}}</li>
        <li>Active: {{english_word.active|yesno}}</li>
    </ul>

    <a href="{% url 'english-edit' english_word.id %}">[Edit]<a> - <a href="{% url 'english-delete' english_word.id %}">[Delete]</a> - <a href="{% url 'english-list' %}">Back to the list</a>

{% endblock %}

vocablizer/listings/templates/listings/english_edit.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1>Edit an English word</h1>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send">
    
{% endblock %}

vocablizer/listings/templates/listings/english_list.html
{% extends 'listings/base.html' %}

{% block content %}


<h1>Home</h1>
<p>This is a website to master any language you want.</p>
<h2>English words:</h2>
<ul> 
    {% for word in words %}
        {% if word.rank == 1 %}
            <li><a href="{% url 'english-detail' word.id%}">{{ word.word|upper }}</a>
            - <a href="{% url 'english-edit' word.id%}">[Edit]</a> </li>
        {% else %}
            <li><a href="{% url 'english-detail' word.id%}">{{ word.word|lower }}</a>
            - <a href="{% url 'english-edit' word.id%}">[Edit]</a> </li>
            {% endif %}
    {% endfor %}
</ul>

<p> Length of english words list : {{ words|length }}</p>

<button><a href="{% url 'english-add' %}">Add a new English word</a></button>

{% endblock %}

vocablizer/listings/templates/listings/example_add.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1>Add a new Example</h1>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Envoyer">
    </form>

{% endblock %}

vocablizer/listings/templates/listings/example_delete.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1>Delete example : {{english_word.word}}</h1>

    <p>Are you sure you want to delete this example?</p>
    
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes, I'm sure.">    
    </form>

{% endblock %}

vocablizer/listings/templates/listings/example_detail.html
{% extends 'listings/base.html' %}

{% block content %}
    <h2> Example of {{example.english}} :</h2>
    <ul>
        <li> {{ example.example }} 
        <li> <a href="{% url 'english-detail' example.english.id%}">{{ example.english }}</a>
        <li> {{ example.created_at }}
        <li> {{ example.updated_at }}
    </ul>

    <a href="{% url 'example-edit' example.id %}">[Edit]</a> - <a href="{% url 'example-delete' example.id %}">[Delete]</a> - <a href="{% url 'example-list' %}">Back to the list</a>

{% endblock %}

vocablizer/listings/templates/listings/example_edit.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1>Edit an example</h1>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send">
    
{% endblock %}

vocablizer/listings/templates/listings/example_list.html
{% extends 'listings/base.html' %}

{% block content %}


<h1>List of all examples</h1>
<ul> 
    {% for example in examples %}
        <h4> Example for <a href="{% url 'example-detail' example.id%}">
            {{ example.english}}</a> <a href="{% url 'example-edit' example.id %}">[Edit]</a>: </h4>
        <p>- {{ example.example }} </p>
    {% endfor %}
</ul>

<button><a href="{% url 'example-add' %}">Add a new example for an english word</a></button>

{% endblock %}